version: 0.0
os: linux
files:
  # S3에서 받은 배포 파일 전체를 서버의 /home/ubuntu/app 폴더로 복사합니다.
  - source: /
    destination: /home/ubuntu/app
    overwrite: yes

permissions:
  # 복사된 파일들의 소유자와 그룹을 ubuntu로 설정합니다.
  - object: /
    pattern: '**'
    owner: ubuntu
    group: ubuntu
    mode: 755

hooks:
  # 배포 완료 이후 애플리케이션 시작 단계에서 deploy.sh 스크립트를 실행합니다.
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 180
      runas: root