spring:
  profiles:
    default: local

  application:
    name: beat-it

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      port: 6379

  kafka:
    consumer:
      group-id: chat-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        
  servlet:
    multipart:
      max-file-size: 300MB
      max-request-size: 300MB

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}

springdoc:
  swagger-ui:
    operations-sorter: method
    tags-sorter: alpha

jwt:
  secret: ${JWT_SECRET}
  expiration: 604800000 # 7 days
  refresh-expiration: 2592000000 # 30 days (rememberMe: true)
  refresh-expiration-short: 604800000 # 7 days (rememberMe: false)

kakao:
  rest-api-key: ${KAKAO_REST_API_KEY}

logging:
  level:
    org.apache.kafka: ERROR
    org.springframework.kafka: ERROR
