server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/beatit_db
  data:
    redis:
      host: localhost
      port: 6379

  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: http://localhost:8080/login/oauth2/code/google

  kafka:
    bootstrap-servers: localhost:9092
