spring:
  application:
    name: beat-it
  datasource:
    url: jdbc:postgresql://localhost:5432/beatit_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379


  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: chat-group
      auto-offset-reset: earliest
      key-deserializer: string
      value-deserializer: string
    producer:
      key-serializer: string
      value-serializer: string

springdoc:
  swagger-ui:
    operations-sorter: method # API를 HTTP 메서드순 정렬 (또는 alpha)
    tags-sorter: alpha        # 태그를 알파벳순 정렬

jwt:
  secret: ${JWT_SECRET:v3rys3cr3tk3yf0rjwtm4k31tL0ng3n0ugh1234567890}
  expiration: 86400000 # 24 hours

kakao:
  rest-api-key: ${KAKAO_REST_API_KEY:}

