server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/beatit_db
  data:
    redis:
      host: localhost
      port: 6379

  kafka:
    bootstrap-servers: localhost:9092

app:
  oauth2:
    authorized-redirect-uri: http://localhost:3000/oauth2/redirect
